Repository pwkamp/AVRmada, pull requests merged in 2025-05, with the labels that each got.

#2 Universally use Tabs rather than Spaces
  AVRmada/include/battleship_utils.h
  AVRmada/include/gfx.h
  AVRmada/src/battleship_utils.c
  AVRmada/src/gfx.c
  AVRmada/src/main.c
Labels: refactor

#12 (feat) Sound Effects
  AVRmada/AVRmada.cproj
  AVRmada/include/battleship_utils.h
  AVRmada/include/buzzer.h
  AVRmada/include/gfx.h
  AVRmada/src/buzzer.c
  AVRmada/src/gfx.c
  AVRmada/src/main.c
Labels: enhancement

#18 Singleplayer mode
  AVRmada/include/battleship_utils.h
  AVRmada/include/singleplayer.h
  AVRmada/src/battleship_utils.c
  AVRmada/src/main.c
  AVRmada/src/singleplayer.c
Labels: enhancement

#17 (feat) EEPROM Image Write and Display
  AVRmada/AVRmada.cproj
  AVRmada/include/buzzer.h
  AVRmada/include/eeprom.h
  AVRmada/include/gfx.h
  AVRmada/include/singleplayer.h
  AVRmada/src/battleship_utils.c
  AVRmada/src/eeprom.c
  AVRmada/src/main.c
Labels: enhancement

#21 temporary string fix
  AVRmada/AVRmada.cproj
  AVRmada/include/battleship_utils.h
  AVRmada/include/eeprom.h
  AVRmada/src/battleship_utils.c
  AVRmada/src/eeprom.c
  AVRmada/src/main.c
Labels: bug
